import { readFile, readlink, realpath, writeFile } from 'node:fs/promises';
import {
  basename,
  dirname,
  isAbsolute,
  join,
  relative,
  resolve,
  sep,
} from 'node:path';

import {
  buildCommandContext,
  type CommandContext,
  type GlobalOptions,
} from '@app/command-context';
import { readGlobalOptions } from '@commands/shared/shared.utils';
import {
  type OatConfig,
  readOatConfig,
  writeOatConfig,
} from '@config/oat-config';
import { CliError } from '@errors/cli-error';
import { dirExists } from '@fs/io';
import { normalizeToPosixPath, resolveProjectRoot } from '@fs/paths';
import { Command, Option } from 'commander';

import { generateIndex, renderIndex } from './generator';

export const GENERATED_INDEX_WARNING =
  '<!-- AUTOGENERATED by `oat docs generate-index`. Do not hand-edit; changes are clobbered on every `predev` / `prebuild`. -->';

const YAML_EXTENSIONS = ['.yml', '.yaml'];

/**
 * Exit codes, per the `packages/cli/AGENTS.md` taxonomy.
 *
 * A refused output target is an actionable user error: the operator passed a
 * path the command will not write to, and the message names what to pass
 * instead. Unusable path *configuration* keeps the exit code the external plan
 * mandates in its step 1, matching the `oat-config.ts` precedent for an invalid
 * repository config value paired with a repair command.
 */
const REFUSAL_EXIT_CODE = 1;
const CONFIGURATION_EXIT_CODE = 2;

interface IndexGenerateOptions {
  docsDir?: string;
  output?: string;
  /** Accumulated `--exclude` values, in the order they were supplied. */
  exclude?: string[];
}

interface IndexGenerateFileDependencies {
  generateIndex: (
    docsDir: string,
    options: import('./generator').GenerateIndexOptions,
  ) => Promise<import('./generator').IndexEntry[]>;
  renderIndex: (entries: import('./generator').IndexEntry[]) => string;
  writeFile: (
    path: string,
    content: string,
    encoding: BufferEncoding,
  ) => Promise<void>;
  readOatConfig: (repoRoot: string) => Promise<OatConfig>;
  writeOatConfig: (repoRoot: string, config: OatConfig) => Promise<void>;
  resolveRepoRoot: (cwd: string) => Promise<string>;
  dirExists: (path: string) => Promise<boolean>;
  readFileIfPresent: (path: string) => Promise<string | null>;
  realpath: (path: string) => Promise<string>;
  readLinkIfSymlink: (path: string) => Promise<string | null>;
}

interface IndexGenerateDependencies {
  buildCommandContext: (options: GlobalOptions) => CommandContext;
  fileDeps: IndexGenerateFileDependencies;
}

async function readFileIfPresent(path: string): Promise<string | null> {
  try {
    return await readFile(path, 'utf8');
  } catch (error) {
    const code = (error as NodeJS.ErrnoException).code;
    if (code === 'ENOENT' || code === 'ENOTDIR') {
      return null;
    }
    throw error;
  }
}

/** The link destination when `path` is a symlink (dangling or not), else null. */
async function readLinkIfSymlink(path: string): Promise<string | null> {
  try {
    return await readlink(path);
  } catch {
    // EINVAL (not a symlink) and ENOENT (absent) are both "nothing to follow".
    return null;
  }
}

const DEFAULT_FILE_DEPS: IndexGenerateFileDependencies = {
  generateIndex,
  renderIndex,
  writeFile,
  readOatConfig,
  writeOatConfig,
  resolveRepoRoot: resolveProjectRoot,
  dirExists,
  readFileIfPresent,
  realpath,
  readLinkIfSymlink,
};

const DEFAULT_DEPENDENCIES: IndexGenerateDependencies = {
  buildCommandContext,
  fileDeps: DEFAULT_FILE_DEPS,
};

function buildGeneratedIndexOutput(content: string): string {
  if (!content) {
    return GENERATED_INDEX_WARNING;
  }

  return `${GENERATED_INDEX_WARNING}\n\n${content}`;
}

/**
 * True when the relative path escapes its base. A bare `startsWith('..')` test
 * is wrong: it also matches ordinary children such as `..draft/page.md`, which
 * would let a target inside the indexed tree pass the safety checks.
 */
function escapesBase(relativePath: string): boolean {
  return (
    isAbsolute(relativePath) ||
    relativePath === '..' ||
    relativePath.startsWith(`..${sep}`)
  );
}

/**
 * True when `candidate` is `parent` itself or lives underneath it. Used for the
 * output-safety checks, so an exact match must count as "inside".
 */
function isAtOrInside(parent: string, candidate: string): boolean {
  const relativePath = relative(parent, candidate);
  return relativePath === '' || !escapesBase(relativePath);
}

/** True when `candidate` lives strictly underneath `parent`. */
function isInside(parent: string, candidate: string): boolean {
  const relativePath = relative(parent, candidate);
  return relativePath !== '' && !escapesBase(relativePath);
}

/**
 * Maximum symlink hops followed while canonicalizing, mirroring the kernel's
 * own bound. `realpath` handles resolvable chains; this only bounds the
 * dangling-link hops resolved below.
 */
const MAX_SYMLINK_HOPS = 32;

/**
 * Absolute path with symlinks resolved, so a symlinked parent cannot smuggle a
 * write into a protected tree past the lexical containment checks.
 *
 * Output paths usually do not exist yet, so `realpath` fails and the nearest
 * existing ancestor is resolved instead. A *dangling* symlink also fails
 * `realpath`, yet `writeFile` still follows it, so read its destination
 * explicitly. Components are resolved parent-first, in filesystem order, so a
 * relative link destination is joined to the parent's *real* location rather
 * than its lexical spelling.
 */
async function canonicalize(
  target: string,
  deps: Pick<IndexGenerateFileDependencies, 'realpath' | 'readLinkIfSymlink'>,
  linkHops = 0,
): Promise<string> {
  const absolute = resolve(target);

  try {
    return await deps.realpath(absolute);
  } catch (error) {
    const code = (error as NodeJS.ErrnoException).code;
    if (code !== 'ENOENT' && code !== 'ENOTDIR') {
      throw error;
    }
  }

  const parent = dirname(absolute);
  if (parent === absolute) {
    return absolute;
  }

  const canonicalParent = await canonicalize(parent, deps, linkHops);
  const candidate = join(canonicalParent, basename(absolute));

  const linkTarget = await deps.readLinkIfSymlink(candidate);
  if (linkTarget === null) {
    return candidate;
  }

  if (linkHops >= MAX_SYMLINK_HOPS) {
    // Fail closed: falling through would hand the writer an unresolved link.
    throw new CliError(
      `Refusing to resolve ${target}: its symlink chain exceeds ${MAX_SYMLINK_HOPS} hops. ` +
        'Pass --output with a path that is not a deep symlink chain.',
      REFUSAL_EXIT_CODE,
    );
  }

  return canonicalize(resolve(canonicalParent, linkTarget), deps, linkHops + 1);
}

function trimmed(value: string | undefined): string | null {
  const trimmedValue = value?.trim();
  return trimmedValue ? trimmedValue : null;
}

/** Commander collector for the repeatable `--exclude` flag. */
function collectExclude(
  value: string,
  previous: string[] | undefined,
): string[] {
  return [...(previous ?? []), value];
}

/**
 * The exclusion list handed to the generator: `documentation.excludes` first,
 * then the `--exclude` flags.
 *
 * Flags **extend** the configured defaults rather than replacing them, so a
 * one-off exclusion on the command line cannot silently republish the pages a
 * repository deliberately excluded. Entries are trimmed, blanks are dropped,
 * and duplicates collapse while preserving first-seen order.
 */
function resolveExcludes(
  config: OatConfig,
  flagValues: string[] | undefined,
): string[] {
  const merged: string[] = [];
  for (const value of [
    ...(config.documentation?.excludes ?? []),
    ...(flagValues ?? []),
  ]) {
    const entry = value.trim();
    if (entry && !merged.includes(entry)) {
      merged.push(entry);
    }
  }
  return merged;
}

type DocsDirSource = 'flag' | 'config-docs-subdirectory' | 'config-root';

interface ResolvedIndexGeneratePaths {
  repoRoot: string;
  config: OatConfig;
  /** Absolute `documentation.root`, or null when it is unset/empty. */
  configuredRoot: string | null;
  docsDir: string;
  docsDirSource: DocsDirSource;
  outputPath: string;
  outputIsExplicit: boolean;
  /** Config defaults extended by `--exclude`, trimmed and de-duplicated. */
  excludes: string[];
}

function missingRootError(flag: '--docs-dir' | '--output'): CliError {
  return new CliError(
    `Cannot resolve ${flag === '--docs-dir' ? 'the docs directory' : 'the output path'}: ` +
      '`documentation.root` is not set in .oat/config.json. ' +
      'Set it with `oat config set documentation.root <path>` (or run `oat docs init`), ' +
      `or pass ${flag} <path> explicitly.`,
    CONFIGURATION_EXIT_CODE,
  );
}

/**
 * Resolve the docs directory and output path.
 *
 * Omitted options come from repository configuration; explicitly supplied
 * options stay CWD-relative for backward compatibility. `documentation.root`
 * canonically names the docs **app root** written by `oat docs init`. The
 * `<root>/docs` preference is compatibility behavior for legacy configs whose
 * `root` names a docs *source* directory; `--docs-dir` overrides it.
 */
async function resolveIndexGeneratePaths(
  context: CommandContext,
  options: IndexGenerateOptions,
  deps: IndexGenerateFileDependencies,
): Promise<ResolvedIndexGeneratePaths> {
  const repoRoot = await deps.resolveRepoRoot(context.cwd);
  const config = await deps.readOatConfig(repoRoot);
  const configuredRootValue = trimmed(config.documentation?.root);
  const configuredRoot = configuredRootValue
    ? resolve(repoRoot, configuredRootValue)
    : null;

  // Either omitted option needs a usable configured root, so validate it once
  // up front rather than only on the path that happens to be derived first.
  if (options.docsDir === undefined || options.output === undefined) {
    if (!configuredRoot) {
      throw missingRootError(
        options.docsDir === undefined ? '--docs-dir' : '--output',
      );
    }
    if (!(await deps.dirExists(configuredRoot))) {
      // Fail with the config-repair path rather than letting the generator or
      // the writer surface a raw ENOENT under the generic exit code.
      throw new CliError(
        `Cannot resolve documentation paths: \`documentation.root\` is set to "${configuredRootValue}" ` +
          `in .oat/config.json, but ${configuredRoot} is not a directory. ` +
          'Repair it with `oat config set documentation.root <path>`, or pass --docs-dir and --output explicitly.',
        CONFIGURATION_EXIT_CODE,
      );
    }
  }

  let docsDir: string;
  let docsDirSource: DocsDirSource;
  if (options.docsDir !== undefined) {
    docsDir = resolve(context.cwd, options.docsDir);
    docsDirSource = 'flag';
  } else if (await deps.dirExists(join(configuredRoot!, 'docs'))) {
    docsDir = join(configuredRoot!, 'docs');
    docsDirSource = 'config-docs-subdirectory';
  } else {
    docsDir = configuredRoot!;
    docsDirSource = 'config-root';
  }

  const outputIsExplicit = options.output !== undefined;
  const outputPath = outputIsExplicit
    ? resolve(context.cwd, options.output!)
    : join(configuredRoot!, 'index.md');

  return {
    repoRoot,
    config,
    configuredRoot,
    docsDir,
    docsDirSource,
    outputPath,
    outputIsExplicit,
    excludes: resolveExcludes(config, options.exclude),
  };
}

/**
 * Symlink-resolved twins of the paths the safety checks compare. Lexical
 * containment alone is bypassable: a symlinked directory inside the app root
 * can point back into the indexed tree.
 */
interface CanonicalIndexGeneratePaths {
  docsDir: string;
  outputPath: string;
  configuredRoot: string | null;
  documentationConfig: string | null;
  lexicalDocumentationConfig: string | null;
}

/** `canonicalize`, but an unresolvable path yields null instead of throwing. */
async function canonicalizeOrNull(
  target: string,
  deps: Pick<IndexGenerateFileDependencies, 'realpath' | 'readLinkIfSymlink'>,
): Promise<string | null> {
  try {
    return await canonicalize(target, deps);
  } catch {
    return null;
  }
}

async function canonicalizeIndexGeneratePaths(
  resolved: ResolvedIndexGeneratePaths,
  deps: IndexGenerateFileDependencies,
): Promise<CanonicalIndexGeneratePaths> {
  const documentationConfigValue = trimmed(
    resolved.config.documentation?.config,
  );

  const lexicalDocumentationConfig = documentationConfigValue
    ? resolve(resolved.repoRoot, documentationConfigValue)
    : null;

  return {
    docsDir: await canonicalize(resolved.docsDir, deps),
    outputPath: await canonicalize(resolved.outputPath, deps),
    // An unusable configured root only makes the config write ineligible; it
    // must not fail a run whose paths were both supplied explicitly.
    configuredRoot: resolved.configuredRoot
      ? await canonicalizeOrNull(resolved.configuredRoot, deps)
      : null,
    lexicalDocumentationConfig,
    // Falling back to the lexical path keeps the refusal guard intact when the
    // configured tool config cannot be canonicalized.
    documentationConfig: lexicalDocumentationConfig
      ? ((await canonicalizeOrNull(lexicalDocumentationConfig, deps)) ??
        lexicalDocumentationConfig)
      : null,
  };
}

/**
 * Reject unsafe output targets before anything is generated or written. Applies
 * to derived and explicit paths alike, and compares canonical paths so a
 * symlinked target cannot slip past. Messages name the operator-supplied path.
 */
async function assertOutputIsSafe(
  resolved: ResolvedIndexGeneratePaths,
  canonical: CanonicalIndexGeneratePaths,
  deps: IndexGenerateFileDependencies,
): Promise<void> {
  const { docsDir, outputPath, outputIsExplicit } = resolved;

  if (isAtOrInside(canonical.docsDir, canonical.outputPath)) {
    throw new CliError(
      `Refusing to write the generated index inside the docs directory it indexes: ` +
        `${outputPath} is inside ${docsDir}. Pass --output with a path outside the docs directory.`,
      REFUSAL_EXIT_CODE,
    );
  }

  const configuredConfigPaths = new Set(
    [
      canonical.documentationConfig,
      canonical.lexicalDocumentationConfig,
    ].filter((value): value is string => value !== null),
  );
  if (
    configuredConfigPaths.has(canonical.outputPath) ||
    configuredConfigPaths.has(outputPath)
  ) {
    throw new CliError(
      `Refusing to overwrite the documentation tool config at ${outputPath} ` +
        '(`documentation.config` in .oat/config.json). Pass --output with a different path.',
      REFUSAL_EXIT_CODE,
    );
  }

  const yamlCandidates = [
    outputPath.toLowerCase(),
    canonical.outputPath.toLowerCase(),
  ];
  if (
    YAML_EXTENSIONS.some((extension) =>
      yamlCandidates.some((candidate) => candidate.endsWith(extension)),
    )
  ) {
    throw new CliError(
      `Refusing to write the generated Markdown index to a YAML file: ${outputPath}. ` +
        'Pass --output with a Markdown path.',
      REFUSAL_EXIT_CODE,
    );
  }

  if (outputIsExplicit) {
    return;
  }

  const existing = await deps.readFileIfPresent(outputPath);
  if (existing !== null && !existing.includes(GENERATED_INDEX_WARNING)) {
    throw new CliError(
      `Refusing to overwrite ${outputPath}: the file exists and is not a generated index ` +
        '(it has no `oat docs generate-index` AUTOGENERATED header). ' +
        'Move or delete it, or pass --output to name it explicitly.',
      REFUSAL_EXIT_CODE,
    );
  }
}

/**
 * The only configuration write this command performs: the Fumadocs bootstrap
 * transition that records the generated app-root manifest in
 * `documentation.index`. MkDocs (and any other declared tooling) never writes.
 */
function isFumadocsManifestTransition(
  resolved: ResolvedIndexGeneratePaths,
  canonical: CanonicalIndexGeneratePaths,
): boolean {
  const { config } = resolved;
  if (
    !canonical.configuredRoot ||
    !isInside(canonical.configuredRoot, canonical.outputPath)
  ) {
    return false;
  }

  const tooling = trimmed(config.documentation?.tooling)?.toLowerCase();
  if (tooling) {
    return tooling === 'fumadocs';
  }

  return trimmed(config.documentation?.config) === null;
}

/**
 * The repo-relative value recorded in `documentation.index`.
 *
 * Eligibility is decided on canonical paths, so an operator who supplied an
 * aliased spelling of the output (`/private/tmp/...` for `/tmp/...`) would
 * otherwise persist a machine-specific path into tracked config. Take the
 * canonical suffix inside the configured root and rebase it onto that root's
 * configured spelling, which is repo-relative by construction.
 */
function buildDocumentationIndexValue(
  resolved: ResolvedIndexGeneratePaths,
  canonical: CanonicalIndexGeneratePaths,
): string | null {
  const suffix = relative(canonical.configuredRoot!, canonical.outputPath);
  const portableOutput = join(resolved.configuredRoot!, suffix);
  const relativeOutput = relative(resolved.repoRoot, portableOutput);
  // An empty relative path means the output *is* the repository root directory,
  // which is never written. A `documentation.root` outside the repository would
  // persist an absolute or `../` path. Withhold the key in both cases rather
  // than record a value pointing at a file this run did not produce.
  if (!relativeOutput || escapesBase(relativeOutput)) {
    return null;
  }
  return normalizeToPosixPath(relativeOutput);
}

async function runIndexGenerate(
  context: CommandContext,
  options: IndexGenerateOptions,
  deps: IndexGenerateFileDependencies,
): Promise<void> {
  const resolved = await resolveIndexGeneratePaths(context, options, deps);
  const canonical = await canonicalizeIndexGeneratePaths(resolved, deps);
  await assertOutputIsSafe(resolved, canonical, deps);

  const { config, docsDir, outputPath, repoRoot } = resolved;

  const entries = await deps.generateIndex(docsDir, {
    excludes: resolved.excludes,
  });
  const content = buildGeneratedIndexOutput(deps.renderIndex(entries));

  await deps.writeFile(outputPath, content, 'utf8');

  if (isFumadocsManifestTransition(resolved, canonical)) {
    const indexPath = buildDocumentationIndexValue(resolved, canonical);
    if (indexPath !== null && config.documentation?.index !== indexPath) {
      await deps.writeOatConfig(repoRoot, {
        ...config,
        documentation: {
          ...config.documentation,
          index: indexPath,
        },
      });
    }
  }

  if (context.json) {
    context.logger.json({
      status: 'ok',
      entriesGenerated: entries.length,
      docsDir,
      docsDirSource: resolved.docsDirSource,
      outputPath,
    });
    return;
  }

  context.logger.info(
    `Generated index with ${entries.length} entries from ${docsDir} → ${outputPath}`,
  );
}

async function runIndexGenerateCommand(
  context: CommandContext,
  options: IndexGenerateOptions,
  dependencies: IndexGenerateDependencies,
): Promise<void> {
  try {
    await runIndexGenerate(context, options, dependencies.fileDeps);
    process.exitCode = 0;
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    if (context.json) {
      context.logger.json({ status: 'error', message });
    } else {
      context.logger.error(message);
    }
    process.exitCode = error instanceof CliError ? error.exitCode : 1;
  }
}

export function createDocsGenerateIndexCommand(
  overrides: Partial<IndexGenerateDependencies> = {},
): Command {
  const dependencies: IndexGenerateDependencies = {
    ...DEFAULT_DEPENDENCIES,
    ...overrides,
  };

  return new Command('generate-index')
    .description('Generate a docs index from markdown files')
    .addOption(
      new Option(
        '--docs-dir <path>',
        'Documentation source directory, resolved from the CWD (default: `<documentation.root>/docs` when that directory exists, otherwise `<documentation.root>`)',
      ),
    )
    .addOption(
      new Option(
        '--output <path>',
        'Output file path, resolved from the CWD (default: `<documentation.root>/index.md`)',
      ),
    )
    .addOption(
      new Option(
        '--exclude <glob>',
        'Exclude matching paths, relative to the docs directory (`*` within a segment, `**` across segments, trailing `/` for directories only). Repeatable, and additive to `documentation.excludes`',
      ).argParser(collectExclude),
    )
    .action(async (options: IndexGenerateOptions, command: Command) => {
      const context = dependencies.buildCommandContext(
        readGlobalOptions(command),
      );
      await runIndexGenerateCommand(context, options, dependencies);
    });
}
